create sequence car_post_seq start with 1 increment by 50;
create sequence owner_post_seq start with 1 increment by 50;
create table car_post (car_price float(53), id bigint not null, owner_post_id bigint not null, car_brand varchar(255), car_city varchar(255), car_contact varchar(255), car_created_date varchar(255), car_description varchar(255), car_egine_version varchar(255), car_model varchar(255), primary key (id));
create table owner_post (id bigint not null, owner_contact_number varchar(255), owner_name varchar(255), owner_type varchar(255), primary key (id));
alter table if exists car_post add constraint FKishsb3g1grg5y00k55c2kb8w1 foreign key (owner_post_id) references owner_post;
create sequence car_post_seq start with 1 increment by 50;
create sequence owner_post_seq start with 1 increment by 50;
create table car_post (car_price float(53), id bigint not null, owner_post_id bigint not null, car_brand varchar(255), car_city varchar(255), car_contact varchar(255), car_created_date varchar(255), car_description varchar(255), car_egine_version varchar(255), car_model varchar(255), primary key (id));
create table owner_post (id bigint not null, owner_contact_number varchar(255), owner_name varchar(255), owner_type varchar(255), primary key (id));
alter table if exists car_post add constraint FKishsb3g1grg5y00k55c2kb8w1 foreign key (owner_post_id) references owner_post;
create sequence car_post_seq start with 1 increment by 50;
create sequence owner_post_seq start with 1 increment by 50;
create table car_post (car_price float(53), id bigint not null, owner_post_id bigint not null, car_brand varchar(255), car_city varchar(255), car_contact varchar(255), car_created_date varchar(255), car_description varchar(255), car_egine_version varchar(255), car_model varchar(255), primary key (id));
create table owner_post (id bigint not null, owner_contact_number varchar(255), owner_name varchar(255), owner_type varchar(255), primary key (id));
alter table if exists car_post add constraint FKishsb3g1grg5y00k55c2kb8w1 foreign key (owner_post_id) references owner_post;
create sequence car_post_seq start with 1 increment by 50;
create sequence owner_post_seq start with 1 increment by 50;
create table car_post (car_price float(53), id bigint not null, owner_post_id bigint not null, car_brand varchar(255), car_city varchar(255), car_contact varchar(255), car_created_date varchar(255), car_description varchar(255), car_egine_version varchar(255), car_model varchar(255), primary key (id));
create table owner_post (id bigint not null, owner_contact_number varchar(255), owner_name varchar(255), owner_type varchar(255), primary key (id));
alter table if exists car_post add constraint FKishsb3g1grg5y00k55c2kb8w1 foreign key (owner_post_id) references owner_post;
create sequence car_post_seq start with 1 increment by 50;
create sequence owner_post_seq start with 1 increment by 50;
create table car_post (car_price float(53), id bigint not null, owner_post_id bigint not null, car_brand varchar(255), car_city varchar(255), car_contact varchar(255), car_created_date varchar(255), car_description varchar(255), car_egine_version varchar(255), car_model varchar(255), primary key (id));
create table owner_post (id bigint not null, owner_contact_number varchar(255), owner_name varchar(255), owner_type varchar(255), primary key (id));
alter table if exists car_post add constraint FKishsb3g1grg5y00k55c2kb8w1 foreign key (owner_post_id) references owner_post;
create sequence car_post_seq start with 1 increment by 50;
create sequence owner_post_seq start with 1 increment by 50;
create table car_post (car_price float(53), id bigint not null, owner_post_id bigint not null, car_brand varchar(255), car_city varchar(255), car_contact varchar(255), car_created_date varchar(255), car_description varchar(255), car_egine_version varchar(255), car_model varchar(255), primary key (id));
create table owner_post (id bigint not null, owner_contact_number varchar(255), owner_name varchar(255), owner_type varchar(255), primary key (id));
alter table if exists car_post add constraint FKishsb3g1grg5y00k55c2kb8w1 foreign key (owner_post_id) references owner_post;
